# Generated by Django 5.0.4 on 2024-04-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_application_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
