# Generated by Django 5.0.4 on 2024-04-22 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_applicant_interview_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='interview_date',
        ),
    ]
